spring:
  datasource:
    url: jdbc:mysql://localhost:3306/myinstagram?serverTimezone=Asia/Seoul
    username: songining
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        #show_sql: true
        format_sql: true
        default_batch_fetch_size: 100
        dialect: org.hibernate.dialect.MySQL57Dialect
    defer-datasource-initialization: true

jwt:
  header: Authorization
  # secret key를 base 64로 인코딩하여 채워넣음
  secret: c2lsdmVybmluZS10ZWNoLXNwcmluZy1ib290LWp3dC10dXRvcmlhbC1zZWNyZXQtc2lsdmVybmluZS10ZWNoLXNwcmluZy1ib290LWp3dC10dXRvcmlhbC1zZWNyZXQK
  token-validity-in-seconds: 86400

logging:
  level:
    org.hibernate.SQL: debug
  # org.hibernate.type: trace

